### ISSUE TITLE
No longer possible to connect to S7-1500 after switching from open ssl to build-in-crypto

### ISSUE THREAD

**Issue by Eldarion85** [node-opcua/node-opcua-crypto#21]
After it didn't work at home i also tried to upgrade our OPC UA connections from Node-RED to the S7-1500 PLC to “build-in-crypto” in the company. Unfortunately here too without success.
I then installed a completely new Node-RED and got a new PLC from storage. Access works with guest access and user login, but only if certificates are not used. As soon as you switch to "Basic256Sha256" in the PLC, a connection is no longer possible. The client reports "check that server has security policy Basic256Sha256". But this is exactly what is set (see link below).
The conclusion: with "build-in-crypto" communication with Siemens controls only works without certificates.
After downgrading to 2.0.307 (open ssl) it immediately works perfectly with the newly installed system. With individual certificates or a certificate chain, everything is possible. But after the upgrade, no chance.

[https://github.com/mikakaraila/node-red-contrib-opcua/issues/577](https://github.com/mikakaraila/node-red-contrib-opcua/issues/577)

**Comment by erossignon** [comment]
Please provide more information about your context:

 - what version of node-opcua-crypto is your application using ?
 - how did you generate the certificate ? 
 - have you exchange the public keys (certificates) so that your application certificate instance is known on the Server side and vice & versa?
 - does your company have a "NodeOPCUA Subscription"  ( see https://support.sterfive.com) ? 
 
this would allow us to investigate your specific support case online.

**Comment by Eldarion85** [comment]
Good morning,

The problem arises when I upgrade the module "node-red-contrib-opcua" from 2.0.307 to 2.0.309 in Node-RED (mikakaraila/node-red-contrib-opcua#577). With newer versions, including 2.0.315, the problem persists. I did not install the module “node-opcua-crypto” manually. But I think the latest version 4.5.0 is used (see screenshot).

![Crypto-Update](https://github.com/node-opcua/node-opcua-crypto/assets/90176159/a5681af6-700b-414a-bcea-1ae828744cfa)

![Crypto-Version](https://github.com/node-opcua/node-opcua-crypto/assets/90176159/0f60c842-984a-4fa1-9922-ab923dbe284e)

I have so many machines running with connections between Node-RED and Siemens S7-1500 that I have now tested almost all combinations.

Debian: 11, 12
NodeJS: 16, 18, 20
Node RED: 4.0.0, 4.0.3
node-opcua-crypto: 4.2.0, 4.5.0
node-red-contrib-opcua: 2.0.307, 2.0.309, 2.0.314, 2.0.315

In the company, the server (Siemens S7-1500) only allows clients with known certificates. The SecurityPolicy is set to "Basic256Sha256 Sign&Encrypt" everywhere. Details can be found in the issues (mikakaraila/node-red-contrib-opcua#577). The client (node-red-contrib-opcua) also has its own certificates. The server and client certificate come from the same root CA. The root CA and intermediate CA are stored in the "./PKI/issuers/certs" folder so that the client can check the S7-1500 certificate chain. Both CAs are of course also in the PLC (server).
This has worked perfectly for years, even with around 80 connections. Since the "node-red-contrib-opcua" module switched to "build-in-crypto", it is no longer possible to connect to the S7-1500 with certificates. If I switch to SecurityPolicy "none" in Node-RED and activate the "Accept client certificates at runtime" option in the S7-1500, it works immediately. You can also log in with your username and password. But no certificates!

To test it, I installed a new machine and allowed all clients in the PLC without checking the certificates. Only the client should check the server's certificate. But that doesn't work either. Even if I put the self-signed certificate from the server (S7-1500) in the "trusted" folder on the client, it doesn't work.

The node only shows the message from the picture, which is definitely not correct because the server has the Security Policy "Basic256Sha256".
![Crypto-Node-RED](https://github.com/node-opcua/node-opcua-crypto/assets/90176159/5381a9d4-2d57-4b67-afb5-1a7904ecce8d)

**Comment by erossignon** [comment]
does your company have a "NodeOPCUA Subscription" ( see https://support.sterfive.com/) ? this would allow us to investigate your specific support case online.

**Comment by Eldarion85** [comment]
I'm not sure if our company already has a “NodeOPCUA subscription”. I will check this and, if necessary, arrange for us to be registered here.

**Comment by Eldarion85** [comment]
We don't have a support contract yet. I sent an email to contact@sterfive.com to order the small business service level agreement.
Do I then have to open a new issue for the current problem via the online portal, or can we continue working with the information from the two existing issues on GitHub?

**Comment by erossignon** [comment]
Thank you, the resolution of the incident will be done using our private portal, in confidentiality.
